package main

import (
	"net/http"
	"time"
)

//ReqMsg ok
type ReqMsg struct {
	Client   string         `json:"client"`
	Headers  http.Header    `json:"headers"`
	Body     string         `json:"body"`
	Cookies  []*http.Cookie `json:"cookies"`
	Host     string         `json:"host"`
	Method   string         `json:"method"`
	URL      string         `json:"url"`
	Fromip   string         `json:"fromip"`
	DateTime time.Time      `json:"datetime"`
}

//Bucket hmm
type Bucket struct {
	ID     string `json:"id"`
	Online bool   `json:"online"`
	Stats  int    `json:"stats"`
}

// CreatePostmanRequest ok
type CreatePostmanRequest struct {
	URL string `json:"url"`
}

//Postman model
type Postman struct {
	Info                    PostmanInfo             `json:"info"`
	Item                    []PostmanItem           `json:"item"`
	ProtocolProfileBehavior ProtocolProfileBehavior `json:"protocolProfileBehavior"`
}

//PostmanInfo model
type PostmanInfo struct {
	ID     string `json:"_postman_id"`
	Name   string `json:"name"`
	Schema string `json:"schema"`
}

// PostmanItem ok
type PostmanItem struct {
	Name     string                `json:"name"`
	Request  PostmanItemRequest    `json:"request"`
	Response []PostmanItemResponse `json:"response"`
}

// PostmanItemRequest ok
type PostmanItemRequest struct {
	Method      string                     `json:"method"`
	Header      []PostmanItemRequestHeader `json:"header"`
	Body        PostmanItemRequestBody     `json:"body,omitempty"`
	URL         PostmanItemRequestURL      `json:"url"`
	Description string                     `json:"description"`
}

// PostmanItemRequestHeader ok
type PostmanItemRequestHeader struct {
	Key   string `json:"key"`
	Name  string `json:"name,omitempty"`
	Value string `json:"value"`
	Type  string `json:"type"`
}

// PostmanItemRequestBody ok
type PostmanItemRequestBody struct {
	Mode    string                        `json:"mode"`
	Raw     string                        `json:"raw"`
	Options PostmanItemRequestBodyOptions `json:"options"`
}

// PostmanItemRequestBodyOptions ok
type PostmanItemRequestBodyOptions struct {
	Raw PostmanItemRequestBodyOptionsRaw `json:"raw"`
}

//PostmanItemRequestBodyOptionsRaw ok
type PostmanItemRequestBodyOptionsRaw struct {
	Language string `json:"language"`
}

// PostmanItemRequestURL ok
type PostmanItemRequestURL struct {
	Raw      string   `json:"raw"`
	Protocol string   `json:"protocol"`
	Host     []string `json:"host"`
	Port     string   `json:"port,omitempty"`
	Path     []string `json:"path"`
}

// PostmanItemResponse ok
type PostmanItemResponse struct {
}

// ProtocolProfileBehavior ok
type ProtocolProfileBehavior struct {
}

/*
// AutoGenerated ops
type AutoGenerated struct {
	Info struct {
		PostmanID string `json:"_postman_id"`
		Name      string `json:"name"`
		Schema    string `json:"schema"`
	} `json:"info"`
	Item []struct {
		Name    string `json:"name"`
		Request struct {
			Method string `json:"method"`
			Header []struct {
				Key   string `json:"key"`
				Name  string `json:"name,omitempty"`
				Value string `json:"value"`
				Type  string `json:"type"`
			} `json:"header"`
			Body struct {
				Mode    string `json:"mode"`
				Raw     string `json:"raw"`
				Options struct {
					Raw struct {
						Language string `json:"language"`
					} `json:"raw"`
				} `json:"options"`
			} `json:"body"`
			URL struct {
				Raw      string   `json:"raw"`
				Protocol string   `json:"protocol"`
				Host     []string `json:"host"`
				Port     string   `json:"port"`
				Path     []string `json:"path"`
			} `json:"url"`
			Description string `json:"description"`
		} `json:"request"`
		Response []interface{} `json:"response"`
	} `json:"item"`
	ProtocolProfileBehavior struct {
	} `json:"protocolProfileBehavior"`
}
*/
