name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ravndal/spuky:$(date +%s)
    - name: Docker Login
      run: docker login -u ${{secrets.dockerhubpuser}} -p $ {{secrets.dockerhubpass}}
    - name: Dcoker Push
      run: docker push ravndal/spuky:$(date +%s)
